### ISSUE TITLE
Pictures in README all show QWERTY?

### ISSUE THREAD

**Issue by Zireael07** [jmjoy/keyboard-layout#2]

**Comment by jmjoy** [comment]
Something the matter?

**Comment by Zireael07** [comment]
Literally what the title says. It was supposed to be a new layout?

**Comment by jmjoy** [comment]
This is just an idea. You can edit the desired key position by yourself.

**Comment by Zireael07** [comment]
This should be made clearer in the README then. I was completely confused...
